import React, { useState, useEffect } from "react";
import { motion } from "motion/react";
import {
  Newspaper,
  RefreshCw,
  Sparkles,
  Zap,
  TrendingUp,
  Globe,
  Loader2,
} from "lucide-react";
import { GoogleGenerativeAI } from "@google/generative-ai";

const NewsAI: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [headline, setHeadline] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const genAI = new GoogleGenerativeAI(
    import.meta.env.VITE_GEMINI_API_KEY as string
  );

  const model = genAI.getGenerativeModel({
    model: "gemini-2.0-flash",
  });

  const fetchHeadline = async () => {
    try {
      setLoading(true);
      setError(null);

      const prompt =
        "Generate one futuristic, optimistic, cinematic headline about global innovation, technology, or creativity.";

      const result = await model.generateContent(prompt);
      const text = result.response.text();

      setHeadline(text);
    } catch (err) {
      setError("AI request failed.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHeadline();
  }, []);

  return (
    <div className="min-h-screen w-full bg-gradient-to-b from-[#020617] via-[#041a2f] to-black text-white px-6 py-20">
      {/* HEADER */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-center mb-12"
      >
        <h1 className="text-5xl font-extrabold bg-gradient-to-r from-cyan-300 to-blue-500 bg-clip-text text-transparent">
          AI‑Generated News Pulse
        </h1>
        <p className="text-cyan-200/80 mt-3 max-w-xl mx-auto">
          Real‑time cinematic headlines generated by Gemini.
        </p>
      </motion.div>

      {/* CARD */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-3xl mx-auto bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-8 shadow-lg"
      >
        <div className="flex items-center gap-3 mb-6">
          <Newspaper className="w-7 h-7 text-cyan-300" />
          <h2 className="text-2xl font-semibold">Today’s Headline</h2>
        </div>

        {loading && (
          <div className="flex items-center gap-3 text-cyan-300">
            <Loader2 className="w-6 h-6 animate-spin" />
            <span>Generating headline...</span>
          </div>
        )}

        {error && (
          <div className="text-red-400 font-medium">
            {error} Try again in a moment.
          </div>
        )}

        {!loading && !error && headline && (
          <p className="text-xl leading-relaxed text-cyan-100">{headline}</p>
        )}

        {/* REFRESH BUTTON */}
        <button
          onClick={fetchHeadline}
          className="mt-8 flex items-center gap-2 px-5 py-3 rounded-xl bg-cyan-300/10 border border-cyan-300/30 hover:bg-cyan-300/20 transition-all"
        >
          <RefreshCw className="w-5 h-5 text-cyan-300" />
          <span className="text-cyan-200 font-medium">Refresh Headline</span>
        </button>
      </motion.div>

      {/* ICON STRIP */}
      <div className="flex justify-center gap-6 mt-16 opacity-70">
        <Sparkles className="w-6 h-6 text-cyan-300" />
        <Zap className="w-6 h-6 text-cyan-300" />
        <TrendingUp className="w-6 h-6 text-cyan-300" />
        <Globe className="w-6 h-6 text-cyan-300" />
      </div>
    </div>
  );
};

export default NewsAI;
